name: Run Tests

on: [push, pull_request]  # Запускать при любом push или PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Клонирует репозиторий
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install pytest  # Устанавливаем pytest
    - run: pip install allure-pytest pytest # Allure
    - run: pytest --alluredir=allure_results auto_test.py -v  # Запускаем тесты
    - run: allure serve allure_results
    - name: Generate Allure report
      if: always()  # Запускать даже при падении тестов
      run: |
        allure generate allure_results --clean -o allure_report
        echo "ALLURE_REPORT=$(pwd)/allure_report" >> $GITHUB_ENV
    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure_report    
      