name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.28.1 pytest==7.4.0 pytest-mock==3.14.0
          pip list  # Для отладки

      - name: Create test-results directory
        run: mkdir -p test-results

      - name: Run tests
        run: |
          pytest test_script.py --junitxml=test-results/report.xml || echo "Tests failed, but continuing"
        continue-on-error: true

      - name: List files
        run: ls -la test-results/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/report.xml
