name: Run Tests with Allure Reporting

on: 
  push:
    branches: [ main, master ]  # Ограничиваем триггер для основных веток
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Важно для работы с gh-pages

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pytest allure-pytest
        
    - name: Run tests
      run: pytest --alluredir=allure_results auto_test.py -v
      
    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install default-jre -y
        curl -o allure-2.24.0.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.tgz
        sudo tar -zxvf allure-2.24.0.tgz -C /opt/
        sudo ln -s /opt/allure-2.24.0/bin/allure /usr/bin/allure
        allure --version
        
    - name: Generate Allure report
      if: always()
      run: |
        allure generate allure_results --clean -o allure_report
        
    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure_report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure_report
        keep_files: true
        force_orphan: true  # Важная настройка для чистого деплоя